INSERT INTO account VALUES (DEFAULT, 'Lili', 1000);
INSERT INTO account VALUES (DEFAULT, 'Jake', 2000);
INSERT INTO account VALUES (DEFAULT, 'Jane', 3000);
INSERT INTO account VALUES (DEFAULT, 'Mark', 0);